#ifndef CONFIG_H
#define CONFIG_H

#define DEFAULT_WINDOW_RATIO_NUM 3
#define DEFAULT_WINDOW_RATIO_DEN 4

#define MIN_WINDOW_WIDTH 640
#define MIN_WINDOW_HEIGHT 480

#define SNAKE_COUNT 18
#define SNAKE_LENGTH 32
#define SNAKE_SIZE 12

#define BASE_SPEED 3
#define MAX_SPEED 12
#define MIN_SPEED 1

#define WINDOW_MOVE_STEP 40
#define FRAME_DELAY_MS 16

#endif
